//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KensBlog_DBSchema_Service.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KensBlogModelContainer : DbContext
    {
        public KensBlogModelContainer()
            : base("name=KensBlogModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Manager> ManagerSet { get; set; }
        public virtual DbSet<OPTLog> OPTLogSet { get; set; }
        public virtual DbSet<Feature> FeatureSet { get; set; }
        public virtual DbSet<Role> RoleSet { get; set; }
    }
}
